/* =========================================================
   1か月（4週間）コース拡張 — Day 8〜28
   data.js の CURRICULUM に追加する。週のメタ情報は WEEKS。
   ========================================================= */

const WEEKS = [
  { week: 1, title: "Week 1：基礎文法", desc: "be動詞〜前置詞。会話の土台をつくる" },
  { week: 2, title: "Week 2：時制と比較を広げる", desc: "進行形・現在完了・比較・不定詞/動名詞" },
  { week: 3, title: "Week 3：表現力アップ", desc: "助動詞の発展・受け身・関係代名詞・ていねい表現" },
  { week: 4, title: "Week 4：実戦会話", desc: "意見・提案・電話・道案内・計画を話す" },
];

CURRICULUM.push(
  /* ================= DAY 8 ================= */
  {
    day: 8, week: 2,
    title: "現在進行形",
    theme: "be + 〜ing（今〜している）",
    grammar: {
      intro: "「今〜している最中だ」を表すのが現在進行形。be動詞 + 動詞のing形で作ります。",
      points: [
        { h: "作り方", p: "am / is / are + 動詞ing。", eg: "I am studying. / She is cooking." },
        { h: "ing形のつくり方", p: "ふつうは+ing、eで終わる語はeを取って+ing、短母音+子音は重ねる。", eg: "make→making / run→running" },
        { h: "否定・疑問", p: "be動詞 + not / be動詞を前に出す。", eg: "He isn't sleeping. / Are you working?" },
        { h: "現在形との違い", p: "現在形＝習慣、進行形＝今まさに。", eg: "I usually walk, but I'm taking the bus today." },
      ],
    },
    vocab: [
      { en: "now", ja: "今" }, { en: "right now", ja: "ちょうど今" }, { en: "look", ja: "見る" },
      { en: "listen", ja: "聞く" }, { en: "wait", ja: "待つ" }, { en: "run", ja: "走る" },
      { en: "cook", ja: "料理する" }, { en: "write", ja: "書く" }, { en: "read", ja: "読む" },
      { en: "watch", ja: "見る/視聴する" }, { en: "sleep", ja: "眠る" }, { en: "wear", ja: "着ている" },
      { en: "rain", ja: "雨が降る" }, { en: "drive", ja: "運転する" }, { en: "sit", ja: "座る" },
      { en: "stand", ja: "立つ" }, { en: "talk", ja: "話す" }, { en: "outside", ja: "外で" },
    ],
    examples: [
      { en: "I'm studying English now.", ja: "今、英語を勉強しています。" },
      { en: "She is cooking dinner.", ja: "彼女は夕食を作っています。" },
      { en: "What are you doing?", ja: "何をしているの？" },
      { en: "It's raining outside.", ja: "外は雨が降っています。" },
      { en: "They are watching TV.", ja: "彼らはテレビを見ています。" },
      { en: "I'm not working today.", ja: "今日は働いていません。" },
    ],
    questions: [
      { type: "choice", q: "She ___ dinner now.", options: ["cook", "cooks", "is cooking", "cooked"], answer: 2, explain: "今〜している＝be動詞+ing。she なので is cooking。" },
      { type: "choice", q: "「run」のing形は？", options: ["runing", "running", "runnning", "runs"], answer: 1, explain: "短母音+子音は子音を重ねて running。" },
      { type: "choice", q: "「彼らは何をしていますか？」", options: ["What they doing?", "What are they doing?", "What do they doing?", "What they are do?"], answer: 1, explain: "疑問詞+be動詞+主語+ing。" },
      { type: "choice", q: "It ___ raining.", options: ["is", "are", "am", "do"], answer: 0, explain: "It は is。" },
      { type: "order", q: "「私は今英語を勉強しています」を並べ替えましょう。", answer: ["I", "am", "studying", "English", "now"], explain: "be動詞+ing。" },
      { type: "order", q: "「あなたは何を見ていますか？」を並べ替えましょう。", answer: ["What", "are", "you", "watching"], explain: "What are you + ing。" },
      { type: "fill", q: "He ___ sleeping.（be動詞）", answer: ["is"], explain: "he は is。" },
      { type: "fill", q: "write のing形は？", answer: ["writing"], explain: "e を取って writing。" },
      { type: "translate", q: "「外は雨が降っています。」を英語にしましょう。", keywords: ["it", "is", "raining"], model: "It is raining outside.", explain: "It is raining。" },
      { type: "translate", q: "「私はテレビを見ています。」を英語にしましょう。", keywords: ["i", "am", "watching", "tv"], model: "I am watching TV.", explain: "be動詞+ing。" },
    ],
  },

  /* ================= DAY 9 ================= */
  {
    day: 9, week: 2,
    title: "過去進行形",
    theme: "was / were + 〜ing（〜していた）",
    grammar: {
      intro: "過去のある時点で「〜していた」を表すのが過去進行形。was/were + 動詞ing です。",
      points: [
        { h: "作り方", p: "I/he/she/it は was、you/we/they は were + 動詞ing。", eg: "I was reading. / They were playing." },
        { h: "否定・疑問", p: "wasn't / weren't、Was/Were + 主語…?", eg: "Were you sleeping?" },
        { h: "when と while", p: "when＝過去の一点、while＝〜している間に。", eg: "I was cooking when he called." },
        { h: "過去形との違い", p: "過去形＝完了した動作、過去進行形＝その時の最中。", eg: "I watched a movie. / I was watching a movie." },
      ],
    },
    vocab: [
      { en: "was", ja: "〜だった/していた" }, { en: "were", ja: "〜だった/していた" }, { en: "while", ja: "〜している間に" },
      { en: "when", ja: "〜のとき" }, { en: "call", ja: "電話する" }, { en: "happen", ja: "起こる" },
      { en: "last night", ja: "昨夜" }, { en: "at that time", ja: "その時" }, { en: "then", ja: "その時/それから" },
      { en: "suddenly", ja: "突然" }, { en: "meet", ja: "会う" }, { en: "walk", ja: "歩く" },
      { en: "wait", ja: "待つ" }, { en: "drive", ja: "運転する" }, { en: "study", ja: "勉強する" },
      { en: "read", ja: "読む" }, { en: "play", ja: "遊ぶ/する" }, { en: "morning", ja: "朝" },
    ],
    examples: [
      { en: "I was watching TV at nine.", ja: "私は9時にテレビを見ていました。" },
      { en: "They were playing soccer.", ja: "彼らはサッカーをしていました。" },
      { en: "What were you doing then?", ja: "その時あなたは何をしていましたか？" },
      { en: "She was sleeping when I called.", ja: "私が電話したとき、彼女は寝ていました。" },
      { en: "We were waiting for the bus.", ja: "私たちはバスを待っていました。" },
      { en: "It was raining this morning.", ja: "今朝は雨が降っていました。" },
    ],
    questions: [
      { type: "choice", q: "They ___ playing soccer.", options: ["was", "were", "are", "is"], answer: 1, explain: "they は were。" },
      { type: "choice", q: "I ___ sleeping when you called.", options: ["was", "were", "am", "did"], answer: 0, explain: "I は was。" },
      { type: "choice", q: "「その時あなたは何をしていましたか？」", options: ["What you were doing?", "What were you doing then?", "What did you doing?", "What are you doing then?"], answer: 1, explain: "What were you + ing。" },
      { type: "choice", q: "She ___ cooking at that time.", options: ["were", "was", "is", "are"], answer: 1, explain: "she は was。" },
      { type: "order", q: "「私は9時にテレビを見ていました」を並べ替えましょう。", answer: ["I", "was", "watching", "TV", "at", "nine"], explain: "was + ing。" },
      { type: "order", q: "「彼らは何をしていましたか？」を並べ替えましょう。", answer: ["What", "were", "they", "doing"], explain: "What were they doing。" },
      { type: "fill", q: "We ___ waiting for the bus.（be動詞の過去・we）", answer: ["were"], explain: "we は were。" },
      { type: "fill", q: "He was ___ a book.（read を ing形に）", answer: ["reading"], explain: "was + reading。" },
      { type: "translate", q: "「私は昨夜勉強していました。」を英語にしましょう。", keywords: ["i", "was", "studying", "last", "night"], model: "I was studying last night.", explain: "was + studying。" },
      { type: "translate", q: "「雨が降っていました。」を英語にしましょう。", keywords: ["it", "was", "raining"], model: "It was raining.", explain: "It was raining。" },
    ],
  },

  /* ================= DAY 10 ================= */
  {
    day: 10, week: 2,
    title: "現在完了",
    theme: "have / has + 過去分詞（経験・完了）",
    grammar: {
      intro: "「〜したことがある（経験）」「〜してしまった（完了）」を表すのが現在完了。have/has + 過去分詞です。",
      points: [
        { h: "経験", p: "ever（今までに）/ never（一度もない）/ before（以前）。", eg: "Have you ever been to Kyoto? / I have never tried it." },
        { h: "完了・結果", p: "just（ちょうど）/ already（すでに）/ yet（まだ・もう）。", eg: "I have just finished. / She hasn't arrived yet." },
        { h: "主語による形", p: "he/she/it は has。", eg: "He has lived here for five years." },
        { h: "for と since", p: "for + 期間、since + 起点。", eg: "for two years / since 2020" },
      ],
    },
    vocab: [
      { en: "have", ja: "〜したことがある(完了)" }, { en: "has", ja: "(3単現)have" }, { en: "already", ja: "すでに" },
      { en: "just", ja: "ちょうど" }, { en: "yet", ja: "まだ/もう" }, { en: "ever", ja: "今までに" },
      { en: "never", ja: "一度も〜ない" }, { en: "before", ja: "以前に" }, { en: "for", ja: "〜の間" },
      { en: "since", ja: "〜以来" }, { en: "been", ja: "be/goの過去分詞" }, { en: "gone", ja: "goの過去分詞" },
      { en: "done", ja: "doの過去分詞" }, { en: "seen", ja: "seeの過去分詞" }, { en: "eaten", ja: "eatの過去分詞" },
      { en: "finish", ja: "終える" }, { en: "arrive", ja: "到着する" }, { en: "visit", ja: "訪れる" },
    ],
    examples: [
      { en: "I have been to Tokyo.", ja: "私は東京に行ったことがあります。" },
      { en: "Have you ever tried natto?", ja: "納豆を食べたことがありますか？" },
      { en: "She has just finished her work.", ja: "彼女はちょうど仕事を終えました。" },
      { en: "I haven't eaten lunch yet.", ja: "まだ昼食を食べていません。" },
      { en: "We have lived here for ten years.", ja: "私たちは10年間ここに住んでいます。" },
      { en: "He has gone home.", ja: "彼は家に帰ってしまいました。" },
    ],
    questions: [
      { type: "choice", q: "I have ___ to Kyoto.", options: ["go", "went", "been", "going"], answer: 2, explain: "現在完了は have + 過去分詞 been。" },
      { type: "choice", q: "She ___ just finished.", options: ["have", "has", "is", "was"], answer: 1, explain: "she は has。" },
      { type: "choice", q: "「あなたは寿司を食べたことがありますか？」", options: ["Did you ever eat sushi?", "Have you ever eaten sushi?", "Are you eaten sushi?", "Do you ate sushi?"], answer: 1, explain: "Have you ever + 過去分詞。" },
      { type: "choice", q: "I haven't done it ___.", options: ["yet", "already", "ago", "since"], answer: 0, explain: "否定文の「まだ」は yet。" },
      { type: "order", q: "「私は東京に行ったことがあります」を並べ替えましょう。", answer: ["I", "have", "been", "to", "Tokyo"], explain: "have been to。" },
      { type: "order", q: "「彼は宿題を終えました」を並べ替えましょう。", answer: ["He", "has", "finished", "his", "homework"], explain: "has + finished。" },
      { type: "fill", q: "We have lived here ___ ten years.（for/since）", answer: ["for"], explain: "期間は for。" },
      { type: "fill", q: "She has ___ lunch.（eat の過去分詞）", answer: ["eaten"], explain: "eat の過去分詞は eaten。" },
      { type: "translate", q: "「私は一度も納豆を食べたことがありません。」を英語にしましょう。", keywords: ["i", "have", "never", "eaten", "natto"], model: "I have never eaten natto.", explain: "have never + 過去分詞。" },
      { type: "translate", q: "「もう宿題は終わりましたか？」を英語にしましょう。", keywords: ["have", "you", "finished", "homework"], model: "Have you finished your homework?", explain: "Have you finished 〜?。" },
    ],
  },

  /* ================= DAY 11 ================= */
  {
    day: 11, week: 2,
    title: "比較級・最上級",
    theme: "-er / -est、more / most、不規則変化",
    grammar: {
      intro: "「〜より…だ」「いちばん…だ」を表す比較の言い方を学びます。",
      points: [
        { h: "比較級（〜より）", p: "形容詞+er + than。", eg: "I'm taller than my brother." },
        { h: "最上級（いちばん）", p: "the + 形容詞+est。", eg: "It's the biggest city in Japan." },
        { h: "長い形容詞", p: "more / most + 形容詞。", eg: "more beautiful / the most famous" },
        { h: "不規則変化", p: "good→better→best、bad→worse→worst。", eg: "This is better than that." },
      ],
    },
    vocab: [
      { en: "tall", ja: "背が高い" }, { en: "big", ja: "大きい" }, { en: "small", ja: "小さい" },
      { en: "fast", ja: "速い" }, { en: "slow", ja: "遅い" }, { en: "cheap", ja: "安い" },
      { en: "expensive", ja: "高価な" }, { en: "beautiful", ja: "美しい" }, { en: "famous", ja: "有名な" },
      { en: "important", ja: "重要な" }, { en: "difficult", ja: "難しい" }, { en: "easy", ja: "簡単な" },
      { en: "better", ja: "より良い" }, { en: "best", ja: "最も良い" }, { en: "worse", ja: "より悪い" },
      { en: "than", ja: "〜より" }, { en: "high", ja: "高い" }, { en: "hot", ja: "暑い/熱い" },
    ],
    examples: [
      { en: "I am taller than my brother.", ja: "私は兄より背が高い。" },
      { en: "This bag is cheaper than that one.", ja: "このかばんはあれより安い。" },
      { en: "Mt. Fuji is the highest mountain in Japan.", ja: "富士山は日本でいちばん高い山です。" },
      { en: "She is more famous than him.", ja: "彼女は彼より有名です。" },
      { en: "Today is hotter than yesterday.", ja: "今日は昨日より暑い。" },
      { en: "This is the best restaurant in town.", ja: "ここは町でいちばんのレストランです。" },
    ],
    questions: [
      { type: "choice", q: "He is ___ than me.", options: ["tall", "taller", "tallest", "more tall"], answer: 1, explain: "比較級は taller + than。" },
      { type: "choice", q: "This is the ___ city in Japan.", options: ["big", "bigger", "biggest", "more big"], answer: 2, explain: "最上級は the biggest。" },
      { type: "choice", q: "「これはあれより高価です」", options: ["This is expensiver than that.", "This is more expensive than that.", "This is most expensive than that.", "This is expensive than that."], answer: 1, explain: "長い形容詞は more + 形容詞。" },
      { type: "choice", q: "good の比較級は？", options: ["gooder", "more good", "better", "best"], answer: 2, explain: "不規則変化で better。" },
      { type: "order", q: "「富士山は日本でいちばん高い山です」を並べ替えましょう。", answer: ["Mt. Fuji", "is", "the", "highest", "mountain", "in", "Japan"], explain: "the highest + 名詞。" },
      { type: "order", q: "「私は兄より背が高い」を並べ替えましょう。", answer: ["I", "am", "taller", "than", "my", "brother"], explain: "比較級 + than。" },
      { type: "fill", q: "Today is ___ than yesterday.（hot の比較級）", answer: ["hotter"], explain: "短母音+子音で hotter。" },
      { type: "fill", q: "She is the ___ famous singer.（most/more）", answer: ["most"], explain: "最上級は the most + 形容詞。" },
      { type: "translate", q: "「この本はあの本より面白い。」を英語にしましょう。", keywords: ["this", "book", "is", "more", "interesting", "than"], model: "This book is more interesting than that one.", explain: "more interesting than。" },
      { type: "translate", q: "「彼女は私より速く走る。」を英語にしましょう。", keywords: ["she", "runs", "faster", "than", "me"], model: "She runs faster than me.", explain: "faster than。" },
    ],
  },

  /* ================= DAY 12 ================= */
  {
    day: 12, week: 2,
    title: "不定詞・動名詞",
    theme: "to + 動詞 / 動詞ing（〜すること）",
    grammar: {
      intro: "「〜すること」「〜するために」を表す to不定詞 と 動名詞(ing) を学びます。",
      points: [
        { h: "to不定詞", p: "to + 動詞の原形。「〜すること」「〜するために」。", eg: "I want to go. / I study to pass the test." },
        { h: "動名詞（〜ing）", p: "主語や目的語になる。", eg: "Swimming is fun. / I like reading." },
        { h: "動詞による使い分け", p: "want / decide / hope は to、enjoy / finish / stop は ing。", eg: "I enjoy cooking. / I decided to study." },
        { h: "like は両方OK", p: "I like to swim = I like swimming.", eg: "I like to read = I like reading." },
      ],
    },
    vocab: [
      { en: "want", ja: "〜したい" }, { en: "hope", ja: "望む" }, { en: "decide", ja: "決める" },
      { en: "plan", ja: "計画する" }, { en: "need", ja: "必要とする" }, { en: "try", ja: "試す" },
      { en: "enjoy", ja: "楽しむ" }, { en: "finish", ja: "終える" }, { en: "stop", ja: "やめる/止まる" },
      { en: "start", ja: "始める" }, { en: "love", ja: "大好き" }, { en: "hate", ja: "嫌う" },
      { en: "learn", ja: "学ぶ" }, { en: "practice", ja: "練習する" }, { en: "swimming", ja: "水泳" },
      { en: "reading", ja: "読書" }, { en: "cooking", ja: "料理" }, { en: "fun", ja: "楽しいこと" },
    ],
    examples: [
      { en: "I want to learn English.", ja: "英語を学びたいです。" },
      { en: "I enjoy reading books.", ja: "私は読書を楽しみます。" },
      { en: "She decided to study abroad.", ja: "彼女は留学を決めました。" },
      { en: "Swimming is good for your health.", ja: "水泳は健康に良いです。" },
      { en: "We finished cleaning the room.", ja: "私たちは部屋の掃除を終えました。" },
      { en: "I hope to see you again.", ja: "また会えるといいですね。" },
    ],
    questions: [
      { type: "choice", q: "I want ___ English.", options: ["learn", "to learn", "learning", "learned"], answer: 1, explain: "want は to + 原形。" },
      { type: "choice", q: "I enjoy ___.", options: ["to read", "read", "reading", "reads"], answer: 2, explain: "enjoy は ing。" },
      { type: "choice", q: "She decided ___ abroad.", options: ["study", "to study", "studying", "studied"], answer: 1, explain: "decide は to + 原形。" },
      { type: "choice", q: "___ is fun.", options: ["Swim", "Swims", "Swimming", "To swimming"], answer: 2, explain: "主語になる動名詞 Swimming。" },
      { type: "order", q: "「私は英語を学びたい」を並べ替えましょう。", answer: ["I", "want", "to", "learn", "English"], explain: "want to + 原形。" },
      { type: "order", q: "「私は料理を楽しみます」を並べ替えましょう。", answer: ["I", "enjoy", "cooking"], explain: "enjoy + ing。" },
      { type: "fill", q: "We finished ___ the room.（clean を ing形に）", answer: ["cleaning"], explain: "finish は ing。" },
      { type: "fill", q: "I hope ___ see you again.（to）", answer: ["to"], explain: "hope to + 原形。" },
      { type: "translate", q: "「私は医者になりたい。」を英語にしましょう。", keywords: ["i", "want", "to", "be", "a", "doctor"], model: "I want to be a doctor.", explain: "want to be 〜。" },
      { type: "translate", q: "「私は読書が好きです。」を英語にしましょう。", keywords: ["i", "like", "reading"], model: "I like reading.", explain: "like + ing（to read でも可）。" },
    ],
  },

  /* ================= DAY 13 ================= */
  {
    day: 13, week: 2,
    title: "接続詞で文をつなぐ",
    theme: "when, if, because, that, before, after",
    grammar: {
      intro: "2つの文をつないで、内容を豊かに伝える接続詞を学びます。",
      points: [
        { h: "時", p: "when（〜のとき）/ before（前に）/ after（後で）/ while（間に）。", eg: "Call me when you arrive." },
        { h: "条件", p: "if（もし〜なら）。未来でも if の中は現在形。", eg: "If it rains, I'll stay home." },
        { h: "理由", p: "because（なぜなら）。", eg: "I'm tired because I worked all day." },
        { h: "that（〜ということ）", p: "I think / know / hope のあとに。", eg: "I think that he is right." },
      ],
    },
    vocab: [
      { en: "when", ja: "〜のとき" }, { en: "if", ja: "もし〜なら" }, { en: "because", ja: "なぜなら" },
      { en: "so", ja: "だから" }, { en: "that", ja: "〜ということ" }, { en: "before", ja: "〜の前に" },
      { en: "after", ja: "〜の後で" }, { en: "while", ja: "〜の間に" }, { en: "think", ja: "思う" },
      { en: "know", ja: "知っている" }, { en: "hope", ja: "望む" }, { en: "believe", ja: "信じる" },
      { en: "sure", ja: "確信して" }, { en: "arrive", ja: "到着する" }, { en: "leave", ja: "出発する" },
      { en: "busy", ja: "忙しい" }, { en: "free", ja: "ひまな" }, { en: "ready", ja: "準備できた" },
    ],
    examples: [
      { en: "Call me when you get home.", ja: "家に着いたら電話して。" },
      { en: "If it rains, we'll stay home.", ja: "もし雨が降ったら、家にいます。" },
      { en: "I think that you are right.", ja: "あなたは正しいと思います。" },
      { en: "I was happy because I passed the test.", ja: "テストに合格したのでうれしかった。" },
      { en: "Let's eat before we go.", ja: "行く前に食べましょう。" },
      { en: "I know that she is busy.", ja: "彼女が忙しいことは知っています。" },
    ],
    questions: [
      { type: "choice", q: "___ it rains, I'll stay home.", options: ["If", "Because", "That", "So"], answer: 0, explain: "条件は If。" },
      { type: "choice", q: "I'm tired ___ I worked a lot.", options: ["if", "because", "that", "before"], answer: 1, explain: "理由は because。" },
      { type: "choice", q: "「あなたが着いたら電話して」", options: ["Call me if you arrive.", "Call me when you arrive.", "Call me that you arrive.", "Call me before arrive."], answer: 1, explain: "「〜のとき」は when。" },
      { type: "choice", q: "I think ___ he is right.", options: ["that", "if", "because", "so"], answer: 0, explain: "I think that 〜。" },
      { type: "order", q: "「もし晴れたら公園に行きます」を並べ替えましょう。", answer: ["If", "it", "is", "sunny", "I", "will", "go", "to", "the", "park"], explain: "If + 現在形, 主節は will。" },
      { type: "order", q: "「私は彼女が忙しいと知っています」を並べ替えましょう。", answer: ["I", "know", "that", "she", "is", "busy"], explain: "know that 〜。" },
      { type: "fill", q: "Let's eat ___ we go.（「〜する前に」）", answer: ["before"], explain: "前に＝before。" },
      { type: "fill", q: "I'm happy ___ it's Friday.（理由）", answer: ["because"], explain: "理由は because。" },
      { type: "translate", q: "「もし疲れているなら、休んでください。」を英語にしましょう。", keywords: ["if", "you", "are", "tired", "rest"], model: "If you are tired, please rest.", explain: "If 〜, please rest。" },
      { type: "translate", q: "「あなたは正しいと思います。」を英語にしましょう。", keywords: ["i", "think", "you", "are", "right"], model: "I think you are right.", explain: "I think (that) you are right。" },
    ],
  },

  /* ================= DAY 14 ================= */
  {
    day: 14, week: 2,
    title: "第2週まとめ・復習",
    theme: "進行形・現在完了・比較・不定詞/動名詞・接続詞",
    grammar: {
      intro: "第2週の総復習です。時制と表現の幅を確認しましょう。",
      points: [
        { h: "進行形", p: "今＝be+ing、過去＝was/were+ing。", eg: "I'm cooking. / I was reading." },
        { h: "現在完了", p: "経験・完了は have/has + 過去分詞。", eg: "I have been to Kyoto." },
        { h: "比較", p: "〜er than / the 〜est / more・most。", eg: "taller than / the best" },
        { h: "不定詞・動名詞・接続詞", p: "want to / enjoy ing / when・if・because。", eg: "I want to go because it's fun." },
      ],
    },
    vocab: [
      { en: "now", ja: "今" }, { en: "yet", ja: "まだ/もう" }, { en: "already", ja: "すでに" },
      { en: "than", ja: "〜より" }, { en: "the best", ja: "最高の" }, { en: "want to", ja: "〜したい" },
      { en: "enjoy", ja: "楽しむ" }, { en: "because", ja: "なぜなら" }, { en: "if", ja: "もし" },
      { en: "when", ja: "〜のとき" }, { en: "been", ja: "be/goの過去分詞" }, { en: "more", ja: "より多く" },
      { en: "while", ja: "〜の間に" }, { en: "decide", ja: "決める" }, { en: "finish", ja: "終える" },
      { en: "important", ja: "重要な" }, { en: "difficult", ja: "難しい" }, { en: "experience", ja: "経験" },
    ],
    examples: [
      { en: "I'm learning English these days.", ja: "最近、英語を学んでいます。" },
      { en: "I have already finished my homework.", ja: "もう宿題を終えました。" },
      { en: "This is more useful than that.", ja: "これはあれより役立ちます。" },
      { en: "I want to travel because I love new places.", ja: "新しい場所が好きなので旅行したい。" },
      { en: "She was cooking when I arrived.", ja: "私が着いたとき彼女は料理していました。" },
      { en: "Learning English is fun.", ja: "英語を学ぶのは楽しい。" },
    ],
    questions: [
      { type: "choice", q: "I have ___ finished.", options: ["yet", "already", "now", "ago"], answer: 1, explain: "肯定の「すでに」は already。" },
      { type: "choice", q: "She ___ cooking when I came.", options: ["is", "was", "were", "has"], answer: 1, explain: "過去進行形 she は was。" },
      { type: "choice", q: "This is ___ than that.", options: ["good", "better", "best", "the best"], answer: 1, explain: "比較級 better + than。" },
      { type: "choice", q: "I enjoy ___ movies.", options: ["to watch", "watch", "watching", "watched"], answer: 2, explain: "enjoy は ing。" },
      { type: "order", q: "「私は京都に行ったことがあります」を並べ替えましょう。", answer: ["I", "have", "been", "to", "Kyoto"], explain: "have been to。" },
      { type: "order", q: "「私は医者になりたい」を並べ替えましょう。", answer: ["I", "want", "to", "be", "a", "doctor"], explain: "want to be。" },
      { type: "fill", q: "Today is ___ than yesterday.（hot の比較級）", answer: ["hotter"], explain: "hotter。" },
      { type: "fill", q: "___ it rains, I'll stay home.（条件の接続詞）", answer: ["if", "If"], explain: "If 〜。" },
      { type: "translate", q: "「私は英語を勉強しています。」を英語にしましょう。", keywords: ["i", "am", "studying", "english"], model: "I am studying English.", explain: "be+ing。" },
      { type: "translate", q: "「これはあれより良いです。」を英語にしましょう。", keywords: ["this", "is", "better", "than", "that"], model: "This is better than that.", explain: "better than。" },
    ],
  },

  /* ================= DAY 15 ================= */
  {
    day: 15, week: 3,
    title: "助動詞の発展",
    theme: "have to / must / may / might / should / shall",
    grammar: {
      intro: "義務・推量・申し出など、気持ちを細かく表す助動詞を広げます。",
      points: [
        { h: "have to（〜しなければ）", p: "must とほぼ同じ。否定 don't have to は「しなくてよい」。", eg: "I have to go. / You don't have to wait." },
        { h: "may / might（〜かもしれない）", p: "may は許可にも使う。", eg: "It might rain. / May I come in?" },
        { h: "should（〜したほうがいい）", p: "had better はより強い助言。", eg: "You should rest. / You'd better hurry." },
        { h: "shall（申し出）", p: "Shall I 〜? で「〜しましょうか」。", eg: "Shall I help you?" },
      ],
    },
    vocab: [
      { en: "have to", ja: "〜しなければ" }, { en: "must", ja: "〜しなければ" }, { en: "may", ja: "〜かもしれない/してよい" },
      { en: "might", ja: "〜かもしれない" }, { en: "should", ja: "〜すべき" }, { en: "shall", ja: "〜しましょうか" },
      { en: "had better", ja: "〜したほうがよい" }, { en: "don't have to", ja: "〜しなくてよい" }, { en: "hurry", ja: "急ぐ" },
      { en: "rest", ja: "休む" }, { en: "careful", ja: "注意深い" }, { en: "late", ja: "遅れて" },
      { en: "early", ja: "早く" }, { en: "perhaps", ja: "もしかすると" }, { en: "probably", ja: "おそらく" },
      { en: "rule", ja: "規則" }, { en: "allow", ja: "許す" }, { en: "maybe", ja: "たぶん" },
    ],
    examples: [
      { en: "I have to finish this today.", ja: "今日これを終えなければなりません。" },
      { en: "You don't have to come.", ja: "来なくても大丈夫ですよ。" },
      { en: "It might rain later.", ja: "あとで雨が降るかもしれません。" },
      { en: "May I use your phone?", ja: "電話を使ってもいいですか？" },
      { en: "Shall I open the window?", ja: "窓を開けましょうか？" },
      { en: "You should see a doctor.", ja: "医者に診てもらったほうがいいですよ。" },
    ],
    questions: [
      { type: "choice", q: "I ___ finish this today.（〜しなければ）", options: ["have to", "may", "shall", "might"], answer: 0, explain: "義務は have to。" },
      { type: "choice", q: "It ___ rain later.（〜かもしれない）", options: ["must", "might", "should", "shall"], answer: 1, explain: "推量は might。" },
      { type: "choice", q: "「窓を開けましょうか？」", options: ["Shall I open the window?", "Should I opened window?", "May open the window?", "Do I open window?"], answer: 0, explain: "申し出は Shall I 〜?。" },
      { type: "choice", q: "You ___ come. It's optional.（〜しなくてよい）", options: ["must not", "don't have to", "should", "have to"], answer: 1, explain: "「しなくてよい」は don't have to。" },
      { type: "order", q: "「あなたは医者に診てもらうべきです」を並べ替えましょう。", answer: ["You", "should", "see", "a", "doctor"], explain: "should + 原形。" },
      { type: "order", q: "「電話を使ってもいいですか？」を並べ替えましょう。", answer: ["May", "I", "use", "your", "phone"], explain: "May I + 原形。" },
      { type: "fill", q: "You ___ hurry, or you'll be late.（had better）", answer: ["had better", "should"], explain: "強い助言 had better（should でも可）。" },
      { type: "fill", q: "I have ___ go now.（to）", answer: ["to"], explain: "have to + 原形。" },
      { type: "translate", q: "「あとで雨が降るかもしれません。」を英語にしましょう。", keywords: ["it", "might", "rain", "later"], model: "It might rain later.", explain: "might + 原形。" },
      { type: "translate", q: "「手伝いましょうか？」を英語にしましょう。", keywords: ["shall", "i", "help", "you"], model: "Shall I help you?", explain: "Shall I 〜?。" },
    ],
  },

  /* ================= DAY 16 ================= */
  {
    day: 16, week: 3,
    title: "受け身（受動態）",
    theme: "be + 過去分詞（〜される）",
    grammar: {
      intro: "「〜される／された」を表す受け身。be動詞 + 過去分詞で作ります。",
      points: [
        { h: "作り方", p: "be動詞 + 過去分詞。", eg: "English is spoken here." },
        { h: "by（〜によって）", p: "動作主を示すときに使う。", eg: "It was made by my mother." },
        { h: "時制", p: "is/are（現在）、was/were（過去）+ 過去分詞。", eg: "The window was broken." },
        { h: "よく使う受け身", p: "be born（生まれる）/ be made of・from。", eg: "I was born in Japan." },
      ],
    },
    vocab: [
      { en: "be made", ja: "作られる" }, { en: "be used", ja: "使われる" }, { en: "be spoken", ja: "話される" },
      { en: "be written", ja: "書かれる" }, { en: "be born", ja: "生まれる" }, { en: "be broken", ja: "壊される" },
      { en: "by", ja: "〜によって" }, { en: "build", ja: "建てる" }, { en: "design", ja: "設計する" },
      { en: "invent", ja: "発明する" }, { en: "paint", ja: "描く/塗る" }, { en: "send", ja: "送る" },
      { en: "clean", ja: "掃除する" }, { en: "find", ja: "見つける" }, { en: "of", ja: "〜の(材料)" },
      { en: "from", ja: "〜から(原料)" }, { en: "temple", ja: "寺" }, { en: "country", ja: "国" },
    ],
    examples: [
      { en: "English is spoken in many countries.", ja: "英語は多くの国で話されています。" },
      { en: "This temple was built 100 years ago.", ja: "この寺は100年前に建てられました。" },
      { en: "I was born in Osaka.", ja: "私は大阪で生まれました。" },
      { en: "The cake was made by my sister.", ja: "そのケーキは姉が作りました。" },
      { en: "These cars are made in Japan.", ja: "これらの車は日本で作られています。" },
      { en: "The window was broken yesterday.", ja: "その窓は昨日壊されました。" },
    ],
    questions: [
      { type: "choice", q: "English ___ in Canada.", options: ["speaks", "is spoken", "speak", "spoke"], answer: 1, explain: "受け身は be + 過去分詞。is spoken。" },
      { type: "choice", q: "This temple ___ 100 years ago.", options: ["builds", "is built", "was built", "built"], answer: 2, explain: "過去の受け身 was built。" },
      { type: "choice", q: "「私は東京で生まれました」", options: ["I born in Tokyo.", "I was born in Tokyo.", "I am bear in Tokyo.", "I were born Tokyo."], answer: 1, explain: "be born で「生まれる」。" },
      { type: "choice", q: "The cake was made ___ my mother.（〜によって）", options: ["by", "from", "of", "with"], answer: 0, explain: "動作主は by。" },
      { type: "order", q: "「これらの車は日本で作られています」を並べ替えましょう。", answer: ["These", "cars", "are", "made", "in", "Japan"], explain: "are + made。" },
      { type: "order", q: "「その窓は壊されました」を並べ替えましょう。", answer: ["The", "window", "was", "broken"], explain: "was + 過去分詞。" },
      { type: "fill", q: "This book ___ written by him.（be動詞・現在）", answer: ["is"], explain: "is written。" },
      { type: "fill", q: "I was ___ in Osaka.（born）", answer: ["born"], explain: "be born。" },
      { type: "translate", q: "「英語は多くの国で話されています。」を英語にしましょう。", keywords: ["english", "is", "spoken", "in", "many", "countries"], model: "English is spoken in many countries.", explain: "is spoken。" },
      { type: "translate", q: "「私は日本で生まれました。」を英語にしましょう。", keywords: ["i", "was", "born", "in", "japan"], model: "I was born in Japan.", explain: "was born。" },
    ],
  },

  /* ================= DAY 17 ================= */
  {
    day: 17, week: 3,
    title: "関係代名詞",
    theme: "who / which / that（名詞を説明する）",
    grammar: {
      intro: "「〜する人／物」のように、名詞をうしろから説明する関係代名詞を学びます。",
      points: [
        { h: "who（人）", p: "人を説明する。", eg: "the man who lives next door" },
        { h: "which / that（物）", p: "物を説明する。", eg: "the book which I bought" },
        { h: "目的格は省略可", p: "目的語の関係代名詞は省ける。", eg: "the movie (that) I watched" },
        { h: "一文にまとめる", p: "2つの文を1つに。", eg: "I have a friend who speaks French." },
      ],
    },
    vocab: [
      { en: "who", ja: "〜する人" }, { en: "which", ja: "〜する物" }, { en: "that", ja: "〜する人/物" },
      { en: "person", ja: "人" }, { en: "thing", ja: "物" }, { en: "friend", ja: "友達" },
      { en: "neighbor", ja: "近所の人" }, { en: "author", ja: "著者" }, { en: "tool", ja: "道具" },
      { en: "place", ja: "場所" }, { en: "someone", ja: "誰か" }, { en: "something", ja: "何か" },
      { en: "live", ja: "住む" }, { en: "work", ja: "働く" }, { en: "buy", ja: "買う" },
      { en: "next door", ja: "隣に" }, { en: "delicious", ja: "おいしい" }, { en: "famous", ja: "有名な" },
    ],
    examples: [
      { en: "I have a friend who lives in London.", ja: "ロンドンに住んでいる友達がいます。" },
      { en: "This is the book that I told you about.", ja: "これが話していた本です。" },
      { en: "The man who is talking is my teacher.", ja: "話している男性は私の先生です。" },
      { en: "Do you know the woman who works here?", ja: "ここで働いている女性を知っていますか？" },
      { en: "The cake which she made was delicious.", ja: "彼女が作ったケーキはおいしかった。" },
      { en: "That's the house that I want to buy.", ja: "あれが私が買いたい家です。" },
    ],
    questions: [
      { type: "choice", q: "I have a friend ___ speaks French.（人）", options: ["which", "who", "what", "whose"], answer: 1, explain: "人は who。" },
      { type: "choice", q: "This is the book ___ I bought.（物）", options: ["who", "which", "where", "when"], answer: 1, explain: "物は which / that。" },
      { type: "choice", q: "「ここで働いている女性」", options: ["the woman which works here", "the woman who works here", "the woman where works here", "the woman works who here"], answer: 1, explain: "人＋who＋動詞。" },
      { type: "choice", q: "The man ___ is talking is my teacher.", options: ["who", "which", "what", "whose"], answer: 0, explain: "人は who。" },
      { type: "order", q: "「ロンドンに住んでいる友達がいます」を並べ替えましょう。", answer: ["I", "have", "a", "friend", "who", "lives", "in", "London"], explain: "friend who lives。" },
      { type: "order", q: "「これは私が買いたい家です」を並べ替えましょう。", answer: ["This", "is", "the", "house", "that", "I", "want", "to", "buy"], explain: "house that I want to buy。" },
      { type: "fill", q: "Do you know the man ___ works here?（人の関係代名詞）", answer: ["who", "that"], explain: "人は who（that も可）。" },
      { type: "fill", q: "The cake ___ she made was great.（物の関係代名詞）", answer: ["which", "that"], explain: "物は which / that。" },
      { type: "translate", q: "「フランス語を話す友達がいます。」を英語にしましょう。", keywords: ["i", "have", "a", "friend", "who", "speaks", "french"], model: "I have a friend who speaks French.", explain: "friend who speaks。" },
      { type: "translate", q: "「これが私が欲しい本です。」を英語にしましょう。", keywords: ["this", "is", "the", "book", "that", "i", "want"], model: "This is the book that I want.", explain: "the book that I want。" },
    ],
  },

  /* ================= DAY 18 ================= */
  {
    day: 18, week: 3,
    title: "ていねい・仮定の表現",
    theme: "would like / Could you / If I were",
    grammar: {
      intro: "ていねいに希望や依頼を伝える表現と、「もし〜なら」の仮定を学びます。",
      points: [
        { h: "would like (to)", p: "want のていねい版。「〜がほしい／〜したい」。", eg: "I'd like a coffee. / I'd like to go." },
        { h: "Could you / Would you", p: "ていねいな依頼。", eg: "Would you help me?" },
        { h: "would（〜だろう）", p: "控えめな予想・感想。", eg: "That would be great." },
        { h: "If I were 〜（もし私が〜なら）", p: "現実と違う仮定。", eg: "If I were you, I would study." },
      ],
    },
    vocab: [
      { en: "would like", ja: "〜がほしい(丁寧)" }, { en: "I'd like to", ja: "〜したい(丁寧)" }, { en: "could you", ja: "〜してもらえますか" },
      { en: "would you", ja: "〜してもらえますか" }, { en: "I'd love to", ja: "ぜひ〜したい" }, { en: "if I were", ja: "もし私が〜なら" },
      { en: "prefer", ja: "〜のほうを好む" }, { en: "rather", ja: "むしろ" }, { en: "mind", ja: "気にする" },
      { en: "favor", ja: "頼みごと" }, { en: "possible", ja: "可能な" }, { en: "appreciate", ja: "感謝する" },
      { en: "instead", ja: "代わりに" }, { en: "request", ja: "依頼" }, { en: "polite", ja: "ていねいな" },
      { en: "advice", ja: "助言" }, { en: "wonderful", ja: "すばらしい" }, { en: "join", ja: "参加する" },
    ],
    examples: [
      { en: "I'd like a cup of tea, please.", ja: "紅茶を一杯いただきたいのですが。" },
      { en: "Would you mind closing the door?", ja: "ドアを閉めていただけますか？" },
      { en: "That would be wonderful.", ja: "それはすばらしいですね。" },
      { en: "If I were you, I would take a rest.", ja: "私があなたなら休みます。" },
      { en: "I'd love to join you.", ja: "ぜひご一緒したいです。" },
      { en: "Could you tell me the way to the station?", ja: "駅までの道を教えてもらえますか？" },
    ],
    questions: [
      { type: "choice", q: "ていねいに「コーヒーがほしい」", options: ["I want coffee.", "I'd like a coffee.", "Give me coffee.", "I like coffee now."], answer: 1, explain: "would like はていねいな希望。" },
      { type: "choice", q: "If I ___ you, I would study.", options: ["am", "was", "were", "be"], answer: 2, explain: "仮定では were を使う。" },
      { type: "choice", q: "「ドアを閉めていただけますか？」", options: ["Would you mind closing the door?", "Do you close door?", "You close the door?", "Close door you?"], answer: 0, explain: "Would you mind + ing。" },
      { type: "choice", q: "That ___ be great.（控えめな予想）", options: ["will", "would", "is", "does"], answer: 1, explain: "would で控えめに。" },
      { type: "order", q: "「駅までの道を教えてもらえますか？」を並べ替えましょう。", answer: ["Could", "you", "tell", "me", "the", "way", "to", "the", "station"], explain: "Could you tell me 〜。" },
      { type: "order", q: "「ぜひご一緒したいです」を並べ替えましょう。", answer: ["I'd", "love", "to", "join", "you"], explain: "I'd love to + 原形。" },
      { type: "fill", q: "I'd ___ to go with you.（〜したい）", answer: ["like", "love"], explain: "I'd like / love to。" },
      { type: "fill", q: "If I ___ rich, I would travel.（仮定の be動詞）", answer: ["were", "was"], explain: "仮定は were（口語で was も）。" },
      { type: "translate", q: "「紅茶を一杯いただきたいのですが。」を英語にしましょう。", keywords: ["i'd", "like", "a", "cup", "of", "tea"], model: "I'd like a cup of tea.", explain: "I'd like 〜。" },
      { type: "translate", q: "「手伝っていただけますか？」を英語にしましょう。", keywords: ["could", "you", "help", "me"], model: "Could you help me?", explain: "Could you 〜?。" },
    ],
  },

  /* ================= DAY 19 ================= */
  {
    day: 19, week: 3,
    title: "量・程度の表現",
    theme: "some/any, much/many, too/enough, a few/a little",
    grammar: {
      intro: "「いくつか・たくさん・〜すぎる・十分」など、量や程度を表す言い方を整理します。",
      points: [
        { h: "some / any", p: "some は肯定文、any は疑問・否定文で。", eg: "I have some money. / Do you have any questions?" },
        { h: "much / many / a lot of", p: "much＝数えない名詞、many＝数えられる名詞、a lot of＝両方。", eg: "much water / many books / a lot of people" },
        { h: "too / enough", p: "too＝〜すぎる、enough＝十分（形容詞のあと）。", eg: "too expensive / good enough" },
        { h: "a few / a little", p: "a few＝（数）少しある、a little＝（量）少しある。", eg: "a few friends / a little time" },
      ],
    },
    vocab: [
      { en: "some", ja: "いくつかの" }, { en: "any", ja: "(疑問/否定)いくつか" }, { en: "much", ja: "(量)多くの" },
      { en: "many", ja: "(数)多くの" }, { en: "a lot of", ja: "たくさんの" }, { en: "a few", ja: "(数)少しの" },
      { en: "a little", ja: "(量)少しの" }, { en: "too", ja: "〜すぎる" }, { en: "enough", ja: "十分な" },
      { en: "more", ja: "もっと多くの" }, { en: "less", ja: "より少ない" }, { en: "several", ja: "いくつかの" },
      { en: "every", ja: "すべての" }, { en: "all", ja: "すべて" }, { en: "both", ja: "両方" },
      { en: "plenty", ja: "たっぷり" }, { en: "only", ja: "〜だけ" }, { en: "question", ja: "質問" },
    ],
    examples: [
      { en: "I have some questions.", ja: "いくつか質問があります。" },
      { en: "Do you have any plans?", ja: "何か予定はありますか？" },
      { en: "There are a lot of people here.", ja: "ここには大勢の人がいます。" },
      { en: "It's too expensive for me.", ja: "私には高すぎます。" },
      { en: "We don't have enough time.", ja: "時間が足りません。" },
      { en: "I have a few friends in Tokyo.", ja: "東京に数人の友達がいます。" },
    ],
    questions: [
      { type: "choice", q: "Do you have ___ questions?", options: ["some", "any", "much", "a little"], answer: 1, explain: "疑問文は any。" },
      { type: "choice", q: "There are ___ books on the desk.（数）", options: ["much", "many", "a little", "any"], answer: 1, explain: "数えられる名詞は many。" },
      { type: "choice", q: "It's ___ expensive. I can't buy it.（〜すぎる）", options: ["too", "enough", "very much", "a little"], answer: 0, explain: "「〜すぎる」は too。" },
      { type: "choice", q: "How ___ water do you drink?（量）", options: ["many", "much", "few", "a lot"], answer: 1, explain: "数えない名詞は much。" },
      { type: "order", q: "「ここには大勢の人がいます」を並べ替えましょう。", answer: ["There", "are", "a lot of", "people", "here"], explain: "a lot of + 名詞。" },
      { type: "order", q: "「時間が足りません」を並べ替えましょう。", answer: ["We", "don't", "have", "enough", "time"], explain: "enough + 名詞。" },
      { type: "fill", q: "I have ___ money.（肯定文の「いくつか/少し」）", answer: ["some"], explain: "肯定文は some。" },
      { type: "fill", q: "I have a ___ friends here.（数が少し）", answer: ["few"], explain: "数は a few。" },
      { type: "translate", q: "「何か予定はありますか？」を英語にしましょう。", keywords: ["do", "you", "have", "any", "plans"], model: "Do you have any plans?", explain: "疑問文 any。" },
      { type: "translate", q: "「私には高すぎます。」を英語にしましょう。", keywords: ["it's", "too", "expensive", "for", "me"], model: "It's too expensive for me.", explain: "too + 形容詞。" },
    ],
  },

  /* ================= DAY 20 ================= */
  {
    day: 20, week: 3,
    title: "表現を広げる（頻度・つなぎ・句動詞）",
    theme: "回数・順序のつなぎ言葉・基本の句動詞",
    grammar: {
      intro: "会話を自然にする頻度表現・順序のつなぎ言葉・よく使う句動詞を学びます。",
      points: [
        { h: "回数・頻度", p: "once a week（週1回）/ twice a day（1日2回）/ every day。", eg: "I exercise twice a week." },
        { h: "順序のつなぎ", p: "first → then → after that → finally。", eg: "First, ... Then, ... Finally, ..." },
        { h: "句動詞①", p: "get up（起きる）/ go to bed / look for（探す）。", eg: "I'm looking for my keys." },
        { h: "句動詞②", p: "turn on/off / put on / take off / pick up。", eg: "Please turn off the light." },
      ],
    },
    vocab: [
      { en: "once", ja: "1回" }, { en: "twice", ja: "2回" }, { en: "three times", ja: "3回" },
      { en: "a week", ja: "週に" }, { en: "these days", ja: "最近" }, { en: "get up", ja: "起きる" },
      { en: "go to bed", ja: "寝る" }, { en: "look for", ja: "探す" }, { en: "turn on", ja: "(電源を)つける" },
      { en: "turn off", ja: "(電源を)消す" }, { en: "give up", ja: "あきらめる" }, { en: "put on", ja: "身につける" },
      { en: "take off", ja: "脱ぐ" }, { en: "pick up", ja: "拾う/迎えに行く" }, { en: "first", ja: "まず" },
      { en: "then", ja: "それから" }, { en: "after that", ja: "その後" }, { en: "finally", ja: "最後に" },
    ],
    examples: [
      { en: "I get up at six every day.", ja: "毎日6時に起きます。" },
      { en: "I exercise twice a week.", ja: "週に2回運動します。" },
      { en: "Could you turn off the light?", ja: "電気を消してもらえますか？" },
      { en: "First, boil the water. Then, add the noodles.", ja: "まずお湯を沸かし、それから麺を入れます。" },
      { en: "I'm looking for my keys.", ja: "鍵を探しています。" },
      { en: "These days, I'm very busy.", ja: "最近とても忙しいです。" },
    ],
    questions: [
      { type: "choice", q: "I exercise ___ a week.（週2回）", options: ["once", "twice", "two", "second"], answer: 1, explain: "2回は twice。" },
      { type: "choice", q: "Could you turn ___ the light? It's dark.（つける）", options: ["on", "off", "up", "in"], answer: 0, explain: "つけるは turn on。" },
      { type: "choice", q: "I'm ___ my keys.（探している）", options: ["looking for", "looking at", "looking up", "look"], answer: 0, explain: "探すは look for。" },
      { type: "choice", q: "順序を表す「最後に」は？", options: ["first", "then", "finally", "after"], answer: 2, explain: "最後に＝finally。" },
      { type: "order", q: "「毎日6時に起きます」を並べ替えましょう。", answer: ["I", "get up", "at", "six", "every day"], explain: "get up at 〜。" },
      { type: "order", q: "「電気を消してもらえますか？」を並べ替えましょう。", answer: ["Could", "you", "turn off", "the", "light"], explain: "turn off the light。" },
      { type: "fill", q: "I go ___ bed at eleven.（寝る：go to ___）", answer: ["to"], explain: "go to bed。" },
      { type: "fill", q: "Don't give ___! You can do it.（あきらめる）", answer: ["up"], explain: "give up。" },
      { type: "translate", q: "「最近とても忙しいです。」を英語にしましょう。", keywords: ["these", "days", "i'm", "very", "busy"], model: "These days, I'm very busy.", explain: "these days で「最近」。" },
      { type: "translate", q: "「私は週に3回走ります。」を英語にしましょう。", keywords: ["i", "run", "three", "times", "a", "week"], model: "I run three times a week.", explain: "three times a week。" },
    ],
  },

  /* ================= DAY 21 ================= */
  {
    day: 21, week: 3,
    title: "第3週まとめ・復習",
    theme: "助動詞・受け身・関係代名詞・ていねい表現・量",
    grammar: {
      intro: "第3週の総復習。表現の幅がぐっと広がりました。使い分けを確認しましょう。",
      points: [
        { h: "助動詞", p: "have to / might / should / Shall I 〜?。", eg: "You should rest. / Shall I help?" },
        { h: "受け身", p: "be + 過去分詞。", eg: "It is made in Japan." },
        { h: "関係代名詞", p: "who（人）/ which・that（物）。", eg: "a friend who lives here" },
        { h: "ていねい・量", p: "I'd like / Could you / some・any / too・enough。", eg: "I'd like some water." },
      ],
    },
    vocab: [
      { en: "have to", ja: "〜しなければ" }, { en: "might", ja: "〜かもしれない" }, { en: "should", ja: "〜すべき" },
      { en: "be made", ja: "作られる" }, { en: "be born", ja: "生まれる" }, { en: "who", ja: "〜する人" },
      { en: "which", ja: "〜する物" }, { en: "would like", ja: "〜がほしい(丁寧)" }, { en: "could you", ja: "〜してもらえますか" },
      { en: "some", ja: "いくつか" }, { en: "any", ja: "(疑問/否定)" }, { en: "too", ja: "〜すぎる" },
      { en: "enough", ja: "十分な" }, { en: "twice", ja: "2回" }, { en: "look for", ja: "探す" },
      { en: "turn off", ja: "消す" }, { en: "finally", ja: "最後に" }, { en: "instead", ja: "代わりに" },
    ],
    examples: [
      { en: "You should try this. It's delicious.", ja: "これ食べてみて。おいしいよ。" },
      { en: "This car is made in Germany.", ja: "この車はドイツ製です。" },
      { en: "I know a place that has great coffee.", ja: "おいしいコーヒーのある場所を知っています。" },
      { en: "I'd like to make a reservation.", ja: "予約をしたいのですが。" },
      { en: "Do you have any time today?", ja: "今日少し時間はありますか？" },
      { en: "Could you turn off the TV?", ja: "テレビを消してもらえますか？" },
    ],
    questions: [
      { type: "choice", q: "You ___ see a doctor.（助言）", options: ["should", "are", "do", "have"], answer: 0, explain: "助言は should。" },
      { type: "choice", q: "This phone is ___ in Japan.（作られる）", options: ["make", "made", "making", "makes"], answer: 1, explain: "受け身 is made。" },
      { type: "choice", q: "a friend ___ lives in Osaka（人）", options: ["which", "who", "where", "what"], answer: 1, explain: "人は who。" },
      { type: "choice", q: "I'd ___ a glass of water.（ていねいに希望）", options: ["want", "like", "love to", "need"], answer: 1, explain: "I'd like + 名詞。" },
      { type: "order", q: "「予約をしたいのですが」を並べ替えましょう。", answer: ["I'd", "like", "to", "make", "a", "reservation"], explain: "I'd like to + 原形。" },
      { type: "order", q: "「テレビを消してもらえますか？」を並べ替えましょう。", answer: ["Could", "you", "turn off", "the", "TV"], explain: "Could you turn off 〜。" },
      { type: "fill", q: "Do you have ___ questions?（疑問文）", answer: ["any"], explain: "疑問文は any。" },
      { type: "fill", q: "I was ___ in Japan.（生まれた）", answer: ["born"], explain: "be born。" },
      { type: "translate", q: "「これはドイツで作られています。」を英語にしましょう。", keywords: ["this", "is", "made", "in", "germany"], model: "This is made in Germany.", explain: "is made in 〜。" },
      { type: "translate", q: "「窓を開けてもらえますか？」を英語にしましょう。", keywords: ["could", "you", "open", "the", "window"], model: "Could you open the window?", explain: "Could you 〜?。" },
    ],
  },

  /* ================= DAY 22 ================= */
  {
    day: 22, week: 4,
    title: "意見・賛成・反対を言う",
    theme: "I think / I agree / I'm not sure",
    grammar: {
      intro: "会話で自分の意見を伝え、賛成・反対を表す表現を学びます。",
      points: [
        { h: "意見を言う", p: "I think / In my opinion / I believe。", eg: "I think it's a good idea." },
        { h: "賛成する", p: "I agree (with you) / That's true / Exactly。", eg: "I agree with you." },
        { h: "やわらかく反対", p: "I'm not sure / I don't think so / I see your point, but…。", eg: "I'm not sure about that." },
        { h: "理由を添える", p: "because / for example でサポート。", eg: "I think so because it's cheaper." },
      ],
    },
    vocab: [
      { en: "think", ja: "思う" }, { en: "opinion", ja: "意見" }, { en: "believe", ja: "信じる/思う" },
      { en: "agree", ja: "賛成する" }, { en: "disagree", ja: "反対する" }, { en: "true", ja: "本当の" },
      { en: "right", ja: "正しい" }, { en: "wrong", ja: "間違った" }, { en: "sure", ja: "確信して" },
      { en: "point", ja: "要点" }, { en: "example", ja: "例" }, { en: "reason", ja: "理由" },
      { en: "idea", ja: "考え" }, { en: "actually", ja: "実は" }, { en: "however", ja: "しかし" },
      { en: "mean", ja: "意味する" }, { en: "feel", ja: "感じる" }, { en: "view", ja: "見方" },
    ],
    examples: [
      { en: "I think it's a great idea.", ja: "いい考えだと思います。" },
      { en: "In my opinion, this is better.", ja: "私の意見では、こちらのほうが良いです。" },
      { en: "I agree with you.", ja: "あなたに賛成です。" },
      { en: "I'm not sure about that.", ja: "それはどうでしょうか（確信が持てません）。" },
      { en: "I don't think so.", ja: "そうは思いません。" },
      { en: "That's a good point.", ja: "それはいい指摘ですね。" },
    ],
    questions: [
      { type: "choice", q: "意見を述べる「私は思う」", options: ["I think", "I agree", "I'm sure not", "I view"], answer: 0, explain: "I think 〜。" },
      { type: "choice", q: "賛成を表すのは？", options: ["I disagree.", "I agree with you.", "I don't think so.", "I'm not sure."], answer: 1, explain: "賛成は I agree。" },
      { type: "choice", q: "やわらかく反対するなら？", options: ["You are wrong.", "No!", "I'm not sure about that.", "That's stupid."], answer: 2, explain: "I'm not sure でやわらかく。" },
      { type: "choice", q: "In my ___, it's too expensive.（意見）", options: ["idea", "opinion", "think", "view of"], answer: 1, explain: "In my opinion。" },
      { type: "order", q: "「いい考えだと思います」を並べ替えましょう。", answer: ["I", "think", "it's", "a", "good", "idea"], explain: "I think it's 〜。" },
      { type: "order", q: "「あなたに賛成です」を並べ替えましょう。", answer: ["I", "agree", "with", "you"], explain: "agree with 〜。" },
      { type: "fill", q: "I don't ___ so.（そう思わない）", answer: ["think"], explain: "I don't think so。" },
      { type: "fill", q: "That's a good ___.（指摘）", answer: ["point"], explain: "good point。" },
      { type: "translate", q: "「私はあなたに賛成です。」を英語にしましょう。", keywords: ["i", "agree", "with", "you"], model: "I agree with you.", explain: "agree with。" },
      { type: "translate", q: "「それはいい考えだと思います。」を英語にしましょう。", keywords: ["i", "think", "it's", "a", "good", "idea"], model: "I think it's a good idea.", explain: "I think it's 〜。" },
    ],
  },

  /* ================= DAY 23 ================= */
  {
    day: 23, week: 4,
    title: "提案・誘う・断る",
    theme: "Let's / Why don't we / How about / Shall we",
    grammar: {
      intro: "相手を誘ったり、提案したり、やわらかく断ったりする会話表現を学びます。",
      points: [
        { h: "提案・誘い", p: "Let's / Why don't we / How about + ing / Shall we 〜?", eg: "How about going to the movies?" },
        { h: "気持ちよく受ける", p: "Sounds good / Sure / I'd love to。", eg: "Sounds good!" },
        { h: "予定を合わせる", p: "Are you free? / What time? / Let's meet at 〜。", eg: "Are you free this weekend?" },
        { h: "やわらかく断る", p: "Sorry, I can't. / I'm busy that day. / Maybe next time。", eg: "Sorry, I can't make it." },
      ],
    },
    vocab: [
      { en: "let's", ja: "〜しましょう" }, { en: "why don't we", ja: "〜しませんか" }, { en: "how about", ja: "〜はどう？" },
      { en: "shall we", ja: "〜しましょうか" }, { en: "free", ja: "ひまな" }, { en: "busy", ja: "忙しい" },
      { en: "join", ja: "参加する" }, { en: "sounds good", ja: "いいね" }, { en: "sure", ja: "もちろん" },
      { en: "next time", ja: "今度" }, { en: "available", ja: "都合がつく" }, { en: "plan", ja: "計画/予定" },
      { en: "meet", ja: "会う" }, { en: "invite", ja: "誘う" }, { en: "together", ja: "一緒に" },
      { en: "weekend", ja: "週末" }, { en: "tonight", ja: "今夜" }, { en: "make it", ja: "都合がつく/行ける" },
    ],
    examples: [
      { en: "Let's have lunch together.", ja: "一緒にランチしましょう。" },
      { en: "Why don't we go to the beach?", ja: "ビーチに行きませんか？" },
      { en: "How about meeting at seven?", ja: "7時に会うのはどうですか？" },
      { en: "Sounds good!", ja: "いいですね！" },
      { en: "Are you free this weekend?", ja: "今週末ひまですか？" },
      { en: "Sorry, I can't make it.", ja: "ごめんなさい、行けません。" },
    ],
    questions: [
      { type: "choice", q: "「映画に行きませんか？」", options: ["How about go to the movies?", "How about going to the movies?", "How about to go movies?", "How go to movies?"], answer: 1, explain: "How about + ing。" },
      { type: "choice", q: "誘いを受ける返事は？", options: ["Sounds good!", "I can't.", "No way.", "I'm busy."], answer: 0, explain: "Sounds good! で快諾。" },
      { type: "choice", q: "___ we meet at six?（〜しましょうか）", options: ["Shall", "Do", "Are", "Let's"], answer: 0, explain: "Shall we 〜?。" },
      { type: "choice", q: "やわらかく断るなら？", options: ["No.", "Sorry, I can't make it.", "I don't want.", "Never."], answer: 1, explain: "Sorry, I can't make it。" },
      { type: "order", q: "「一緒にランチしましょう」を並べ替えましょう。", answer: ["Let's", "have", "lunch", "together"], explain: "Let's + 原形。" },
      { type: "order", q: "「今週末ひまですか？」を並べ替えましょう。", answer: ["Are", "you", "free", "this", "weekend"], explain: "Are you free 〜?。" },
      { type: "fill", q: "___ don't we go out tonight?（〜しませんか）", answer: ["Why", "why"], explain: "Why don't we 〜?。" },
      { type: "fill", q: "I'd ___ to join you.（ぜひ）", answer: ["love"], explain: "I'd love to。" },
      { type: "translate", q: "「7時に会うのはどうですか？」を英語にしましょう。", keywords: ["how", "about", "meeting", "at", "seven"], model: "How about meeting at seven?", explain: "How about + ing。" },
      { type: "translate", q: "「一緒に映画を見ましょう。」を英語にしましょう。", keywords: ["let's", "watch", "a", "movie", "together"], model: "Let's watch a movie together.", explain: "Let's + 原形。" },
    ],
  },

  /* ================= DAY 24 ================= */
  {
    day: 24, week: 4,
    title: "電話・予約・問い合わせ",
    theme: "電話のかけ方・予約・お店への問い合わせ",
    grammar: {
      intro: "電話や予約、お店への問い合わせで使う定番フレーズを学びます。",
      points: [
        { h: "電話", p: "Hello, this is 〜. / May I speak to 〜? / Can I leave a message?", eg: "Hello, this is Ken speaking." },
        { h: "予約", p: "I'd like to make a reservation for 〜.", eg: "A table for two at seven, please." },
        { h: "問い合わせ", p: "Could you tell me 〜? / What time do you open?", eg: "What time do you close?" },
        { h: "確認・聞き返し", p: "Let me check. / Just a moment. / Could you repeat that?", eg: "Could you repeat that, please?" },
      ],
    },
    vocab: [
      { en: "this is", ja: "(電話)こちらは〜" }, { en: "speak to", ja: "〜と話す" }, { en: "message", ja: "伝言" },
      { en: "reservation", ja: "予約" }, { en: "book", ja: "予約する" }, { en: "appointment", ja: "(面会の)予約" },
      { en: "available", ja: "空いている" }, { en: "open", ja: "開く/開いている" }, { en: "close", ja: "閉まる" },
      { en: "hold on", ja: "(電話で)お待ちを" }, { en: "wrong number", ja: "間違い電話" }, { en: "confirm", ja: "確認する" },
      { en: "cancel", ja: "取り消す" }, { en: "repeat", ja: "繰り返す" }, { en: "table", ja: "テーブル/席" },
      { en: "for two", ja: "2名で" }, { en: "leave a message", ja: "伝言を残す" }, { en: "moment", ja: "瞬間/少し" },
    ],
    examples: [
      { en: "Hello, this is Ken speaking.", ja: "もしもし、ケンです。" },
      { en: "May I speak to Mr. Smith?", ja: "スミスさんはいらっしゃいますか？" },
      { en: "I'd like to make a reservation for two.", ja: "2名で予約をお願いします。" },
      { en: "What time do you open?", ja: "何時に開きますか？" },
      { en: "Can I leave a message?", ja: "伝言をお願いできますか？" },
      { en: "Could you repeat that, please?", ja: "もう一度言ってもらえますか？" },
    ],
    questions: [
      { type: "choice", q: "電話で自分を名乗るとき", options: ["I am Ken here.", "This is Ken speaking.", "Here Ken is.", "My speaking Ken."], answer: 1, explain: "This is 〜 speaking。" },
      { type: "choice", q: "「スミスさんはいらっしゃいますか？」", options: ["May I speak to Mr. Smith?", "Can I talk Mr. Smith?", "Is Mr. Smith you?", "Speak Mr. Smith?"], answer: 0, explain: "May I speak to 〜?。" },
      { type: "choice", q: "「2名で予約したいのですが」", options: ["I want table two.", "I'd like to make a reservation for two.", "Reserve two me.", "Two reservation please me."], answer: 1, explain: "make a reservation for 〜。" },
      { type: "choice", q: "「何時に閉まりますか？」", options: ["What time you close?", "What time do you close?", "When close you?", "How time close?"], answer: 1, explain: "What time do you close?。" },
      { type: "order", q: "「伝言をお願いできますか？」を並べ替えましょう。", answer: ["Can", "I", "leave", "a", "message"], explain: "leave a message。" },
      { type: "order", q: "「もう一度言ってもらえますか？」を並べ替えましょう。", answer: ["Could", "you", "repeat", "that"], explain: "Could you repeat that?。" },
      { type: "fill", q: "Hello, ___ is Ken.（電話で名乗る）", answer: ["this"], explain: "this is 〜。" },
      { type: "fill", q: "What time do you ___?（開く）", answer: ["open"], explain: "do you open?。" },
      { type: "translate", q: "「2名で予約をお願いします。」を英語にしましょう。", keywords: ["i'd", "like", "to", "make", "a", "reservation", "for", "two"], model: "I'd like to make a reservation for two.", explain: "make a reservation for two。" },
      { type: "translate", q: "「もう一度言ってもらえますか？」を英語にしましょう。", keywords: ["could", "you", "repeat", "that"], model: "Could you repeat that?", explain: "Could you repeat that?。" },
    ],
  },

  /* ================= DAY 25 ================= */
  {
    day: 25, week: 4,
    title: "道案内・交通・観光",
    theme: "道のたずね方・乗り物・観光のひとこと",
    grammar: {
      intro: "外出先で困らないための、道案内・交通・観光の実用表現です。",
      points: [
        { h: "道をたずねる", p: "How do I get to 〜? / Where is 〜? / Is it far?", eg: "How do I get to the museum?" },
        { h: "道案内する", p: "Go straight / Turn left / It's next to 〜.", eg: "Go straight and turn left." },
        { h: "交通", p: "take the train/bus / get on・off / change trains / How much is the fare?", eg: "Take the bus and get off at the third stop." },
        { h: "観光", p: "Where can I buy a ticket? / Can you recommend 〜?", eg: "Can you recommend a good restaurant?" },
      ],
    },
    vocab: [
      { en: "get to", ja: "〜へ着く" }, { en: "far", ja: "遠い" }, { en: "near", ja: "近い" },
      { en: "straight", ja: "まっすぐ" }, { en: "turn", ja: "曲がる" }, { en: "corner", ja: "角" },
      { en: "across from", ja: "〜の向かい" }, { en: "next to", ja: "〜の隣" }, { en: "between", ja: "〜の間" },
      { en: "train", ja: "電車" }, { en: "subway", ja: "地下鉄" }, { en: "get on", ja: "乗る" },
      { en: "get off", ja: "降りる" }, { en: "change", ja: "乗り換える" }, { en: "fare", ja: "運賃" },
      { en: "ticket", ja: "切符" }, { en: "map", ja: "地図" }, { en: "recommend", ja: "おすすめする" },
    ],
    examples: [
      { en: "How do I get to the museum?", ja: "美術館へはどう行けばいいですか？" },
      { en: "Go straight and turn left at the corner.", ja: "まっすぐ行って角を左に曲がってください。" },
      { en: "It's across from the station.", ja: "それは駅の向かいにあります。" },
      { en: "Take the bus and get off at the third stop.", ja: "バスに乗って3つ目で降りてください。" },
      { en: "How much is the fare?", ja: "運賃はいくらですか？" },
      { en: "Can you recommend a good restaurant?", ja: "良いレストランをおすすめできますか？" },
    ],
    questions: [
      { type: "choice", q: "「美術館へはどう行きますか？」", options: ["How I get museum?", "How do I get to the museum?", "Where go museum?", "How to museum I go?"], answer: 1, explain: "How do I get to 〜?。" },
      { type: "choice", q: "「角を左に曲がって」", options: ["Turn left at the corner.", "Left turn corner the.", "At corner turn the left.", "Corner the left turn."], answer: 0, explain: "Turn left at the corner。" },
      { type: "choice", q: "バスを「降りる」は？", options: ["get on", "get off", "get up", "get to"], answer: 1, explain: "降りるは get off。" },
      { type: "choice", q: "It's ___ the station.（〜の向かい）", options: ["across from", "on", "in", "between"], answer: 0, explain: "向かいは across from。" },
      { type: "order", q: "「まっすぐ行ってください」を並べ替えましょう。", answer: ["Go", "straight", "please"], explain: "Go straight。" },
      { type: "order", q: "「運賃はいくらですか？」を並べ替えましょう。", answer: ["How", "much", "is", "the", "fare"], explain: "How much is the fare?。" },
      { type: "fill", q: "Take the train and get ___ at Tokyo.（降りる）", answer: ["off"], explain: "get off。" },
      { type: "fill", q: "It's ___ to the bank.（〜の隣）", answer: ["next"], explain: "next to。" },
      { type: "translate", q: "「駅はどこですか？」を英語にしましょう。", keywords: ["where", "is", "the", "station"], model: "Where is the station?", explain: "Where is 〜?。" },
      { type: "translate", q: "「良いレストランをおすすめできますか？」を英語にしましょう。", keywords: ["can", "you", "recommend", "a", "good", "restaurant"], model: "Can you recommend a good restaurant?", explain: "recommend 〜。" },
    ],
  },

  /* ================= DAY 26 ================= */
  {
    day: 26, week: 4,
    title: "感情・体調・お願い・トラブル",
    theme: "気持ち・体調を伝える／助けを求める",
    grammar: {
      intro: "気持ちや体調を伝え、困ったときに助けを求める表現を学びます。",
      points: [
        { h: "感情", p: "I'm happy / sad / worried / excited / nervous。", eg: "I'm so excited!" },
        { h: "体調", p: "I have a cold / a headache. / I feel sick. / I'm tired.", eg: "I have a headache." },
        { h: "お願い・助け", p: "Can you help me? / Could you do me a favor?", eg: "Could you do me a favor?" },
        { h: "トラブル", p: "I lost my 〜. / It's not working. / I'm in trouble.", eg: "I lost my passport." },
      ],
    },
    vocab: [
      { en: "happy", ja: "うれしい" }, { en: "sad", ja: "悲しい" }, { en: "worried", ja: "心配な" },
      { en: "excited", ja: "わくわくした" }, { en: "nervous", ja: "緊張した" }, { en: "tired", ja: "疲れた" },
      { en: "sick", ja: "気分が悪い" }, { en: "cold", ja: "風邪" }, { en: "fever", ja: "熱" },
      { en: "headache", ja: "頭痛" }, { en: "stomachache", ja: "腹痛" }, { en: "hurt", ja: "痛む/傷つける" },
      { en: "favor", ja: "頼みごと" }, { en: "trouble", ja: "困りごと" }, { en: "lost", ja: "なくした" },
      { en: "broken", ja: "壊れた" }, { en: "help", ja: "助ける" }, { en: "feel", ja: "感じる" },
    ],
    examples: [
      { en: "I'm so excited about the trip!", ja: "旅行がとても楽しみです！" },
      { en: "I have a headache.", ja: "頭が痛いです。" },
      { en: "I feel a little sick today.", ja: "今日は少し気分が悪いです。" },
      { en: "Could you do me a favor?", ja: "お願いがあるのですが。" },
      { en: "I lost my passport.", ja: "パスポートをなくしました。" },
      { en: "My phone isn't working.", ja: "スマホが動きません。" },
    ],
    questions: [
      { type: "choice", q: "「頭が痛いです」", options: ["I have a headache.", "I am headache.", "My head pain.", "I headache have."], answer: 0, explain: "have a headache。" },
      { type: "choice", q: "「お願いがあるのですが」", options: ["Do me favor you?", "Could you do me a favor?", "Favor me do you?", "You favor me do?"], answer: 1, explain: "do me a favor。" },
      { type: "choice", q: "I'm ___ about the exam.（心配）", options: ["excited", "worried", "happy", "hungry"], answer: 1, explain: "心配は worried。" },
      { type: "choice", q: "「スマホが動きません」", options: ["My phone not work.", "My phone isn't working.", "My phone no working.", "Phone my broken work."], answer: 1, explain: "isn't working。" },
      { type: "order", q: "「私はパスポートをなくしました」を並べ替えましょう。", answer: ["I", "lost", "my", "passport"], explain: "lost my 〜。" },
      { type: "order", q: "「私はとても緊張しています」を並べ替えましょう。", answer: ["I'm", "very", "nervous"], explain: "I'm + 感情。" },
      { type: "fill", q: "I have a ___.（熱）", answer: ["fever"], explain: "have a fever。" },
      { type: "fill", q: "Can you ___ me?（助ける）", answer: ["help"], explain: "help me。" },
      { type: "translate", q: "「今日は気分が悪いです。」を英語にしましょう。", keywords: ["i", "feel", "sick", "today"], model: "I feel sick today.", explain: "feel sick。" },
      { type: "translate", q: "「財布をなくしました。」を英語にしましょう。", keywords: ["i", "lost", "my", "wallet"], model: "I lost my wallet.", explain: "lost my wallet。" },
    ],
  },

  /* ================= DAY 27 ================= */
  {
    day: 27, week: 4,
    title: "計画・夢・経験を語る",
    theme: "be going to / 夢を語る / 経験を話す",
    grammar: {
      intro: "これからの計画や夢、これまでの経験を語る、会話が広がる表現です。",
      points: [
        { h: "計画", p: "be going to / plan to / I'm thinking of + ing。", eg: "I'm going to travel next year." },
        { h: "夢・希望", p: "I want to / My dream is to / Someday I'll 〜。", eg: "My dream is to live abroad." },
        { h: "経験を語る", p: "I've been to / When I was young / I once 〜。", eg: "I've been to three countries." },
        { h: "予測", p: "I think 〜 will / probably。", eg: "I think it will be fun." },
      ],
    },
    vocab: [
      { en: "going to", ja: "〜する予定" }, { en: "plan to", ja: "〜する計画" }, { en: "dream", ja: "夢" },
      { en: "goal", ja: "目標" }, { en: "future", ja: "未来" }, { en: "someday", ja: "いつか" },
      { en: "abroad", ja: "海外で" }, { en: "travel", ja: "旅行する" }, { en: "save money", ja: "お金を貯める" },
      { en: "challenge", ja: "挑戦" }, { en: "experience", ja: "経験" }, { en: "achieve", ja: "達成する" },
      { en: "wish", ja: "願う" }, { en: "probably", ja: "おそらく" }, { en: "opportunity", ja: "機会" },
      { en: "succeed", ja: "成功する" }, { en: "grow", ja: "成長する" }, { en: "start", ja: "始める" },
    ],
    examples: [
      { en: "I'm going to study abroad next year.", ja: "来年留学する予定です。" },
      { en: "My dream is to travel around the world.", ja: "私の夢は世界中を旅することです。" },
      { en: "I want to start my own business.", ja: "自分の事業を始めたいです。" },
      { en: "I've been to three countries.", ja: "3か国に行ったことがあります。" },
      { en: "Someday, I'll live by the sea.", ja: "いつか海のそばに住みます。" },
      { en: "I'm thinking of learning French.", ja: "フランス語を学ぼうと考えています。" },
    ],
    questions: [
      { type: "choice", q: "I'm going ___ travel next year.", options: ["to", "for", "at", "of"], answer: 0, explain: "be going to + 原形。" },
      { type: "choice", q: "「私の夢は海外に住むことです」", options: ["My dream is live abroad.", "My dream is to live abroad.", "My dream living abroad.", "My dream to lives abroad."], answer: 1, explain: "My dream is to + 原形。" },
      { type: "choice", q: "I've ___ to Korea.（行ったことがある）", options: ["been", "gone", "go", "went"], answer: 0, explain: "経験は have been to。" },
      { type: "choice", q: "I'm thinking ___ learning Spanish.（〜しようと考えている）", options: ["of", "to", "for", "at"], answer: 0, explain: "think of + ing。" },
      { type: "order", q: "「来年留学する予定です」を並べ替えましょう。", answer: ["I'm", "going", "to", "study", "abroad", "next", "year"], explain: "be going to + 原形。" },
      { type: "order", q: "「自分の事業を始めたいです」を並べ替えましょう。", answer: ["I", "want", "to", "start", "my", "own", "business"], explain: "want to + 原形。" },
      { type: "fill", q: "My ___ is to be a teacher.（夢）", answer: ["dream"], explain: "My dream is to 〜。" },
      { type: "fill", q: "___, I'll travel the world.（いつか）", answer: ["Someday", "someday"], explain: "Someday 〜。" },
      { type: "translate", q: "「私は世界中を旅したいです。」を英語にしましょう。", keywords: ["i", "want", "to", "travel", "around", "the", "world"], model: "I want to travel around the world.", explain: "want to + 原形。" },
      { type: "translate", q: "「来年、英語を勉強する予定です。」を英語にしましょう。", keywords: ["i'm", "going", "to", "study", "english", "next", "year"], model: "I'm going to study English next year.", explain: "be going to + 原形。" },
    ],
  },

  /* ================= DAY 28 ================= */
  {
    day: 28, week: 4,
    title: "1か月総まとめ・卒業",
    theme: "全範囲の総復習＋実戦ロールプレイ",
    grammar: {
      intro: "1か月お疲れさまでした！ここまでの全範囲を総まとめします。あとは実際に話して身につけましょう。",
      points: [
        { h: "時制を使い分ける", p: "現在・過去・未来・進行形・現在完了。", eg: "I have studied English for a month." },
        { h: "意見・提案・依頼", p: "I think / How about / Could you。", eg: "How about practicing every day?" },
        { h: "実用フレーズ", p: "道案内・電話・予約・トラブル対応。", eg: "I'd like to make a reservation." },
        { h: "これからの学び方", p: "毎日少しずつ、声に出して、実際に使う。", eg: "Keep practicing and never give up!" },
      ],
    },
    vocab: [
      { en: "practice", ja: "練習する" }, { en: "keep", ja: "続ける" }, { en: "improve", ja: "上達する" },
      { en: "confident", ja: "自信がある" }, { en: "fluent", ja: "流暢な" }, { en: "mistake", ja: "間違い" },
      { en: "every day", ja: "毎日" }, { en: "out loud", ja: "声に出して" }, { en: "review", ja: "復習する" },
      { en: "progress", ja: "進歩" }, { en: "continue", ja: "続ける" }, { en: "real", ja: "実際の" },
      { en: "conversation", ja: "会話" }, { en: "useful", ja: "役立つ" }, { en: "thanks to", ja: "〜のおかげで" },
      { en: "proud", ja: "誇らしい" }, { en: "enjoy", ja: "楽しむ" }, { en: "never give up", ja: "あきらめない" },
    ],
    examples: [
      { en: "I have studied English for a month.", ja: "私は1か月英語を勉強しました。" },
      { en: "How about practicing every day?", ja: "毎日練習するのはどうですか？" },
      { en: "Don't be afraid of making mistakes.", ja: "間違いを恐れないで。" },
      { en: "I'd like to make a reservation, please.", ja: "予約をしたいのですが。" },
      { en: "Keep practicing and never give up!", ja: "練習を続けて、あきらめないで！" },
      { en: "I'm proud of my progress.", ja: "自分の進歩を誇りに思います。" },
    ],
    questions: [
      { type: "choice", q: "I have ___ English for a month.（現在完了）", options: ["study", "studied", "studying", "studies"], answer: 1, explain: "have + 過去分詞 studied。" },
      { type: "choice", q: "「毎日練習するのはどうですか？」", options: ["How about practice every day?", "How about practicing every day?", "How practice every day?", "How about to practice daily?"], answer: 1, explain: "How about + ing。" },
      { type: "choice", q: "Don't be afraid of ___ mistakes.（間違える）", options: ["make", "making", "to make", "made"], answer: 1, explain: "of + ing で making。" },
      { type: "choice", q: "ていねいに依頼「窓を開けてもらえますか？」", options: ["Open window?", "Could you open the window?", "You open window please?", "Window open you?"], answer: 1, explain: "Could you 〜?。" },
      { type: "order", q: "「予約をしたいのですが」を並べ替えましょう。", answer: ["I'd", "like", "to", "make", "a", "reservation"], explain: "I'd like to + 原形。" },
      { type: "order", q: "「練習を続けて、あきらめないで！」を並べ替えましょう。", answer: ["Keep", "practicing", "and", "never", "give up"], explain: "Keep + ing。" },
      { type: "fill", q: "I'm proud ___ my progress.（〜を誇りに思う）", answer: ["of"], explain: "be proud of 〜。" },
      { type: "fill", q: "I have been to Kyoto ___.（以前に）", answer: ["before"], explain: "経験の before。" },
      { type: "translate", q: "「私は1か月英語を勉強しました。」を英語にしましょう。", keywords: ["i", "have", "studied", "english", "for", "a", "month"], model: "I have studied English for a month.", explain: "have studied 〜 for a month。" },
      { type: "translate", q: "「あきらめないで！」を英語にしましょう。", keywords: ["never", "give", "up"], model: "Never give up!", explain: "Never give up!。" },
    ],
  }
);

// 追加したDayにも設問数を設定
CURRICULUM.forEach((d) => { d.totalQuestions = d.questions.length; });
